on:
  workflow_dispatch:
    inputs:
      single_repo:
        description: 'Single repository to update'
        required: false
        type: string
  schedule:
    - cron: '15 8 */3 * *'

name: Launch Scala Steward

jobs:
  scala-steward:
    runs-on: ubuntu-latest
    name: Launch Scala Steward
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec
        with:
          git_user_signingkey: true
          git_commit_gpgsign: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Create temporary repos file for single repo
        if: ${{ github.event.inputs.single_repo }}
        run: |
          echo "- nationalarchives/${{ github.event.inputs.single_repo }}:scala-steward-dependencies" > temp-repos.md
      - name: Launch Scala Steward
        uses: scala-steward-org/scala-steward-action@5021652c555c5724af574758b78ea5be49640007
        with:
          github-token: ${{ secrets.WORKFLOW_PAT }}
          sign-commits: true
          signing-key: ${{ secrets.GPG_KEY_ID }}
          author-email: ${{ steps.import_gpg.outputs.email }}
          author-name: ${{ steps.import_gpg.outputs.name }}
          repos-file: ${{ github.event.inputs.single_repo && 'temp-repos.md' || 'repos.md' }}