name: Tag and release TDR Github Actions
on:
  push:
    branches:
      - main
jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    # Skip if the commit is from dependabot updating self-references
    if: |
      !contains(github.event.head_commit.message, 'nationalarchives/tdr-github-actions') ||
      !contains(github.event.head_commit.author.name, 'dependabot')
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - id: next-tag
        uses: nationalarchives/tdr-github-actions/.github/actions/get-next-version@f52edf22c81f568202369a3b31da0277541b0507 # v0.0.11
        with:
          repo-name: tdr-github-actions
      - name: Create tag and release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ steps.next-tag.outputs.next-version }}
          git push origin ${{ steps.next-tag.outputs.next-version }}
          gh release create ${{ steps.next-tag.outputs.next-version }}
